import { defineProperties, createSprinkles } from '@vanilla-extract/sprinkles';
import vars, {
  borderStyles,
  borderWidths,
  breakpoints,
  gridColumns,
  sizes,
} from './vars.css';

const responsiveProperties = defineProperties({
  conditions: {
    initial: {},
    xs: { '@media': breakpoints.xs },
    sm: { '@media': breakpoints.sm },
    md: { '@media': breakpoints.md },
    lg: { '@media': breakpoints.lg },
    xl: { '@media': breakpoints.xl },
  },
  defaultCondition: 'initial',
  properties: {
    all: ['unset'],
    boxSizing: ['border-box'],
    position: ['relative', 'absolute', 'static', 'fixed', 'sticky', 'unset'],
    width: sizes,
    height: sizes,
    minWidth: sizes,
    maxWidth: sizes,
    minHeight: sizes,
    maxHeight: sizes,
    padding: vars.space,
    paddingTop: vars.space,
    paddingBottom: vars.space,
    paddingLeft: vars.space,
    paddingRight: vars.space,
    margin: vars.space,
    marginTop: vars.space,
    marginLeft: vars.space,
    marginRight: vars.space,
    marginBottom: vars.space,
    fontFamily: vars.fonts,
    top: vars.space,
    bottom: vars.space,
    fontSize: vars.fontSizes,
    lineHeight: vars.lineHeights,
    textAlign: ['left', 'center', 'right'],
    fontWeight: vars.fontWeights,
    letterSpacing: vars.letterSpacings,
    textTransform: ['lowercase', 'uppercase', 'unset'],
    display: [
      'none',
      'flex',
      'block',
      'inline',
      'inline-block',
      'inline-flex',
      'unset',
      'contents',
    ],
    flexDirection: ['row', 'column', 'column-reverse', 'row-reverse'],
    justifySelf: [
      'auto',
      'stretch',
      'center',
      'flex-start',
      'flex-end',
      'baseline',
      'initial',
      'inherit',
    ],
    justifyContent: [
      'stretch',
      'flex-start',
      'center',
      'flex-end',
      'space-around',
      'space-between',
      'space-evenly',
    ],
    alignItems: ['stretch', 'flex-start', 'center', 'flex-end'],
    alignSelf: ['start', 'center', 'end', 'stretch'],
    flexWrap: ['wrap', 'wrap-reverse', 'nowrap', 'unset'],
    flexShrink: [0, 1, 2],
    flexGrow: [0, 1, 2, 3],
    flexBasis: [
      'auto',
      'content',
      'fit-content',
      'min-content',
      'max-content',
      'unset',
      0,
    ],
    gridColumn: gridColumns,
    columnGap: vars.space,
    rowGap: vars.space,
    gap: vars.space,
    order: [0, 1, 2, 3],
    color: vars.colours,
    backgroundColor: vars.colours,
    backgroundPosition: ['center', 'right'],
    backgroundSize: ['cover', 'contain'],
    backgroundRepeat: ['no-repeat'],
    borderRadius: vars.radii,
    borderTopLeftRadius: vars.radii,
    borderTopRightRadius: vars.radii,
    borderBottomLeftRadius: vars.radii,
    borderBottomRightRadius: vars.radii,
    borderStyle: borderStyles,
    borderWidth: borderWidths,
    outline: ['none'],
    overflow: ['scroll', 'hidden', 'auto', 'clip', 'visible'],
    opacity: [0.3, 0.5],
    stroke: vars.colours,
    strokeWidth: [0, 1, 2],
    fill: vars.colours,
    cursor: ['pointer'],
  },
  shorthands: {
    // margin
    m: ['margin'],
    mx: ['marginLeft', 'marginRight'],
    my: ['marginTop', 'marginBottom'],
    mt: ['marginTop'],
    mb: ['marginBottom'],
    ml: ['marginLeft'],
    mr: ['marginRight'],
    // padding
    p: ['padding'],
    px: ['paddingLeft', 'paddingRight'],
    py: ['paddingTop', 'paddingBottom'],
    pt: ['paddingTop'],
    pb: ['paddingBottom'],
    pl: ['paddingLeft'],
    pr: ['paddingRight'],
    // border radius
    r: ['borderRadius'],
    rt: ['borderTopLeftRadius', 'borderTopRightRadius'],
    rb: ['borderBottomLeftRadius', 'borderBottomRightRadius'],
  },
});

export const sprinkles = createSprinkles(responsiveProperties);

export type Sprinkles = Parameters<typeof sprinkles>[0];
